mm-video: fix additional arithmetic on a pointer to void
Use char* instead of void* for this
pointer arithmetic. Fixes the following:

Change-Id: I32f267b5b5b88b24787a46311cb9175d6ec0449f
error: arithmetic on a pointer to void
Signed-off-by: DHOMD <DHO@dho.im>